services:
  curator:
    build:
      context: extensions/curator/
    container_name: ${CONTAINER_EXTENSION_CURATOR_NAME}
    init: true
    volumes:
      - ./extensions/curator/config/curator.yml:/.curator/curator.yml:ro,Z
      - ./extensions/curator/config/delete_log_files_curator.yml:/.curator/delete_log_files_curator.yml:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - elasticsearch
