services:
  enterprise-search:
    build:
      context: extensions/enterprise-search/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: ${CONTAINER_EXTENSION_ENTERPRISE_SEARCH_NAME}
    volumes:
      - ./extensions/enterprise-search/config/enterprise-search.yml:/usr/share/enterprise-search/config/enterprise-search.yml:ro,Z
    environment:
      JAVA_OPTS: -Xms2g -Xmx2g
      ENT_SEARCH_DEFAULT_PASSWORD: 'changeme'
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    ports:
      - ${EXTENSION_ENTERPRISE_SEARCH_PORT}:${EXTENSION_ENTERPRISE_SEARCH_PORT}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - elasticsearch
